/* ==========================================================================
   ⚠️ AUTOGENERATED RUNTIME BUNDLE - DO NOT EDIT DIRECTLY!
   Source Directory: js/parent/modules/
   Mọi chỉnh sửa trực tiếp vào tệp này sẽ bị ghi đè khi chạy build.
   ========================================================================== */

// --- Module: js/parent/modules/auth.controller.js ---
/**
 * PARENT PORTAL - AUTH CONTROLLER
 * Xử lý mã PIN, phiên đăng nhập, Kiosk Lock & Graceful Exit
 */
(function(root) {
    'use strict';
    const AuthController = {
        verifyPin: async function(enteredPin) {
            if (!enteredPin) return false;
            try {
                const res = await fetch('/api/auth/verify-pin', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({ pin: enteredPin })
                });
                const data = await res.json();
                return data.success === true;
            } catch (e) {
                console.error("[ParentAuth] Lỗi kết nối xác thực PIN:", e);
                return false;
            }
        },
        exitKioskGracefully: function() {
            if (typeof window !== 'undefined' && window.electronAPI && window.electronAPI.exitApp) {
                window.electronAPI.exitApp();
            } else {
                window.close();
            }
        },
        lockDashboard: function() {
            const overlay = document.getElementById('parent-lock-overlay');
            if (overlay) overlay.classList.remove('hidden');
        }
    };
    if (typeof window !== 'undefined') window.ParentAuthController = AuthController;
    if (typeof module !== 'undefined' && module.exports) module.exports = AuthController;
})(typeof window !== 'undefined' ? window : global);


// --- Module: js/parent/modules/chart.renderer.js ---
/**
 * PARENT PORTAL - CHART RENDERER
 * Vẽ biểu đồ năng lực học tập, thời gian học, điểm yếu (Chart.js)
 */
(function(root) {
    'use strict';
    const ChartRenderer = {
        charts: {},
        renderProgressChart: function(canvasId, labels, data) {
            if (typeof Chart === 'undefined') return null;
            const ctx = document.getElementById(canvasId);
            if (!ctx) return null;
            if (this.charts[canvasId]) this.charts[canvasId].destroy();
            this.charts[canvasId] = new Chart(ctx, {
                type: 'line',
                data: {
                    labels: labels || ['T2', 'T3', 'T4', 'T5', 'T6', 'T7', 'CN'],
                    datasets: [{
                        label: 'Số câu đúng',
                        data: data || [15, 20, 25, 18, 30, 40, 35],
                        borderColor: '#3b82f6',
                        backgroundColor: 'rgba(59, 130, 246, 0.1)',
                        fill: true,
                        tension: 0.4
                    }]
                },
                options: { responsive: true, maintainAspectRatio: false }
            });
            return this.charts[canvasId];
        }
    };
    if (typeof window !== 'undefined') window.ParentChartRenderer = ChartRenderer;
    if (typeof module !== 'undefined' && module.exports) module.exports = ChartRenderer;
})(typeof window !== 'undefined' ? window : global);


// --- Module: js/parent/modules/student.manager.js ---
/**
 * PARENT PORTAL - STUDENT MANAGER
 * Quản lý danh sách 3 học sinh chuẩn (Bình Minh, Đức Phúc, Bảo Ngọc) theo Rule 14
 */
(function(root) {
    'use strict';
    const StudentManager = {
        students: [
            { id: "std_htsj4gbmo", name: "Trần Bình Minh", classLevel: "6", parentEmail: "skyprotect@gmail.com" },
            { id: "std_baongoc", name: "Trần Bảo Ngọc", classLevel: "1", parentEmail: "skyprotect@gmail.com" },
            { id: "std_tyc0gfnkz", name: "Trần Đức Phúc", classLevel: "4", parentEmail: "nhematseo@gmail.com" }
        ],
        getActiveStudent: function() {
            const id = localStorage.getItem('parent_active_student_id') || 'std_htsj4gbmo';
            return this.students.find(s => s.id === id) || this.students[0];
        },
        setActiveStudent: function(studentId) {
            localStorage.setItem('parent_active_student_id', studentId);
            if (typeof window !== 'undefined' && window.parentDashboard) {
                window.parentDashboard.refresh();
            }
        }
    };
    if (typeof window !== 'undefined') window.ParentStudentManager = StudentManager;
    if (typeof module !== 'undefined' && module.exports) module.exports = StudentManager;
})(typeof window !== 'undefined' ? window : global);


// --- Module: js/parent/modules/history.viewer.js ---
/**
 * PARENT PORTAL - HISTORY VIEWER
 * Xem lại lịch sử làm bài thi, phân tích sai sót từng câu hỏi
 */
(function(root) {
    'use strict';
    const HistoryViewer = {
        async loadHistory(studentId) {
            try {
                const res = await fetch(`/api/progress/history?student_id=${studentId}`);
                if (res.ok) return await res.json();
            } catch (e) {}
            return [];
        },
        renderHistoryList(containerId, historyItems) {
            const container = document.getElementById(containerId);
            if (!container) return;
            if (!historyItems || historyItems.length === 0) {
                container.innerHTML = '<p class="text-slate-400 text-center py-6">Chưa có bài thi nào được ghi nhận.</p>';
                return;
            }
            container.innerHTML = historyItems.map(item => `
                <div class="p-3 mb-2 rounded-lg bg-slate-800 border border-slate-700 flex justify-between items-center">
                    <div>
                        <div class="font-bold text-white">${item.lessonTitle || 'Bài luyện tập'}</div>
                        <div class="text-xs text-slate-400">${item.date || 'Hôm nay'} • ${item.score}/10 điểm</div>
                    </div>
                    <span class="px-2.5 py-1 text-xs font-bold rounded-full ${item.score >= 8 ? 'bg-emerald-500/20 text-emerald-400' : 'bg-amber-500/20 text-amber-400'}">
                        ${item.score >= 8 ? 'Đạt' : 'Cần cố gắng'}
                    </span>
                </div>
            `).join('');
        }
    };
    if (typeof window !== 'undefined') window.ParentHistoryViewer = HistoryViewer;
    if (typeof module !== 'undefined' && module.exports) module.exports = HistoryViewer;
})(typeof window !== 'undefined' ? window : global);


// --- Module: js/parent/modules/remote.sync.js ---
/**
 * PARENT PORTAL - REMOTE SYNC
 * Đồng bộ đám mây Firestore & Cập nhật Gemini API Keys
 */
(function(root) {
    'use strict';
    const RemoteSync = {
        async loadApiKeys() {
            try {
                const res = await fetch('/api/settings/gemini-keys');
                if (res.ok) return await res.json();
            } catch (e) {}
            return [];
        },
        async saveApiKeys(keys) {
            try {
                const res = await fetch('/api/settings/gemini-keys', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({ keys })
                });
                return res.ok;
            } catch (e) { return false; }
        }
    };
    if (typeof window !== 'undefined') window.ParentRemoteSync = RemoteSync;
    if (typeof module !== 'undefined' && module.exports) module.exports = RemoteSync;
})(typeof window !== 'undefined' ? window : global);


// --- Module: js/parent/index.js ---
/**
 * PARENT PORTAL - MASTER ORCHESTRATOR
 * Điều phối các module quản lý phụ huynh
 */
(function(root) {
    'use strict';
    class ParentDashboard {
        constructor() {
            this.auth = root.ParentAuthController;
            this.chart = root.ParentChartRenderer;
            this.students = root.ParentStudentManager;
            this.history = root.ParentHistoryViewer;
            this.sync = root.ParentRemoteSync;
        }
        init() {
            console.log('[ParentDashboard] Đã khởi tạo hệ thống quản lý phụ huynh.');
            this.refresh();
        }
        refresh() {
            const student = this.students ? this.students.getActiveStudent() : null;
            if (student) {
                const nameEl = document.getElementById('parent-active-student-name');
                if (nameEl) nameEl.innerText = student.name;
            }
        }
    }
    const dashboard = new ParentDashboard();
    if (typeof window !== 'undefined') {
        window.parentDashboard = dashboard;
        document.addEventListener('DOMContentLoaded', () => dashboard.init());
    }
    if (typeof module !== 'undefined' && module.exports) module.exports = dashboard;
})(typeof window !== 'undefined' ? window : global);


