/**
 * emoji-utils — Bộ tiện ích tra cứu Emoji minh họa từ vựng Tiếng Anh.
 * Độc lập hoàn toàn, hỗ trợ UMD (Node.js CommonJS, Web Workers, Browser Global).
 * 
 * Public Contract:
 * - getWordEmoji(word: string): string
 * - EMOJI_FALLBACK: Record<string, string>
 * - FALLBACK_EMOJI: string ("⭐")
 */
(function (root, factory) {
    const api = factory();
    if (typeof module === 'object' && typeof module.exports === 'object') {
        module.exports = api;
    }
    root.EmojiUtils = api;
    root.getWordEmoji = api.getWordEmoji;
    root.EMOJI_FALLBACK = api.EMOJI_FALLBACK;
    if (typeof window !== 'undefined') {
        window.EmojiUtils = api;
        window.getWordEmoji = api.getWordEmoji;
        window.EMOJI_FALLBACK = api.EMOJI_FALLBACK;
    }
    if (typeof globalThis !== 'undefined') {
        globalThis.EmojiUtils = api;
        globalThis.getWordEmoji = api.getWordEmoji;
        globalThis.EMOJI_FALLBACK = api.EMOJI_FALLBACK;
    }
    if (typeof self !== 'undefined') {
        self.EmojiUtils = api;
        self.getWordEmoji = api.getWordEmoji;
        self.EMOJI_FALLBACK = api.EMOJI_FALLBACK;
    }
})(typeof globalThis !== 'undefined' ? globalThis : typeof window !== 'undefined' ? window : typeof self !== 'undefined' ? self : this, function () {
    'use strict';

    const FALLBACK_EMOJI = "⭐";

    const EMOJI_FALLBACK = {
        "hello": "👋",
        "goodbye": "👋",
        "name": "📛",
        "what": "❓",
        "you": "👤",
        "book": "📖",
        "pen": "🖊️",
        "ruler": "📏",
        "bag": "🎒",
        "pencil": "✏️",
        "red": "🔴",
        "blue": "🔵",
        "green": "🟢",
        "yellow": "🟡",
        "circle": "⭕",
        "one": "1️⃣",
        "two": "2️⃣",
        "three": "3️⃣",
        "four": "4️⃣",
        "five": "5️⃣",
        "father": "👨",
        "mother": "👩",
        "brother": "👦",
        "sister": "👧",
        "baby": "👶",
        "head": "🙆",
        "face": "👩",
        "hand": "✋",
        "foot": "🦶",
        "hair": "💇",
        "ball": "⚽",
        "doll": "🧸",
        "train": "🚂",
        "car": "🚗",
        "plane": "✈️",
        "dog": "🐶",
        "cat": "🐱",
        "bird": "🐦",
        "duck": "🦆",
        "sun": "☀️",
        "apple": "🍎",
        "banana": "🍌",
        "milk": "🥛",
        "cake": "🍰",
        "water": "💧",
        "run": "🏃",
        "walk": "🚶",
        "jump": "🦘",
        "dance": "💃",
        "sing": "🎤",
        "draw": "🎨",
        "speak": "🗣️",
        "house": "🏠",
        "bedroom": "🛏️",
        "living room": "🛋️",
        "kitchen": "🍳",
        "bathroom": "🚿",
        "bed": "🛏️",
        "table": "table",
        "chair": "🪑",
        "sofa": "🛋️",
        "tv": "📺",
        "shirt": "👕",
        "pants": "👖",
        "dress": "👗",
        "shoes": "👟",
        "hat": "👒",
        "orange": "🍊",
        "grape": "🍇",
        "mango": "🥭",
        "strawberry": "🍓",
        "pear": "🍐",
        "cow": "🐄",
        "horse": "🐎",
        "pig": "🐖",
        "sheep": "🐑",
        "chicken": "🐔",
        "lion": "🦁",
        "tiger": "🐯",
        "elephant": "🐘",
        "monkey": "🐒",
        "zebra": "🦓",
        "sky": "☁️",
        "teacher": "🧑‍🏫",
        "doctor": "🧑‍⚕️",
        "pilot": "🧑‍✈️",
        "cook": "🧑‍🍳",
        "driver": "🧑‍✈️",
        "bus": "🚌",
        "vietnam": "🇻🇳",
        "america": "🇺🇸",
        "england": "🇬🇧",
        "japan": "🇯🇵",
        "malaysia": "🇲🇾",
        "australia": "🇦🇺",
        "vietnamese": "🇻🇳",
        "american": "🇺🇸",
        "english": "🇬🇧",
        "japanese": "🇯🇵",
        "malaysian": "🇲🇾",
        "australian": "🇦🇺",
        "time": "⏰",
        "clock": "🕒",
        "morning": "🌅",
        "afternoon": "☀️",
        "evening": "🌇",
        "monday": "📅",
        "tuesday": "📅",
        "wednesday": "📅",
        "thursday": "📅",
        "friday": "📅",
        "saturday": "📅",
        "sunday": "📅",
        "january": "🗓️",
        "february": "🗓️",
        "march": "🗓️",
        "date": "📅",
        "birthday": "🎂",
        "swim": "🏊",
        "cycle": "🚴",
        "skate": "⛸️",
        "paint": "🎨",
        "chess": "♟️",
        "football": "⚽",
        "maths": "🧮",
        "science": "🔬",
        "art": "🎨",
        "music": "🎵",
        "it": "💻",
        "history": "📚",
        "bakery": "🍞",
        "bookshop": "📚",
        "supermarket": "🛒",
        "pharmacy": "💊",
        "cinema": "🎬",
        "zoo": "🦁",
        "sunny": "☀️",
        "rainy": "🌧️",
        "windy": "💨",
        "cloudy": "☁️",
        "stormy": "⚡",
        "snowy": "❄️",
        "spring": "🌸",
        "summer": "☀️",
        "autumn": "🍂",
        "winter": "❄️",
        "fever": "🤒",
        "headache": "🤕",
        "cough": "😷",
        "sore throat": "🤢",
        "stomach ache": "🤮",
        "hometown": "🏡",
        "village": "🏡",
        "city": "🏙️",
        "island": "🏝️",
        "timetable": "📅",
        "story": "📖",
        "visit": "🎒",
        "dentist": "🧑‍⚕️",
        "medicine": "💊",
        "left": "⬅️",
        "right": "➡️",
        "straight": "⬆️",
        "station": "🚉",
        "astronaut": "🧑‍🚀",
        "calculator": "🧮",
        "compass": "🧭",
        "schoolbag": "🎒",
        "pencil sharpener": "✏️",
        "uniform": "👔",
        "wardrobe": " wardrobe",
        "fridge": " Fridge",
        "cooker": " Cooker",
        "tall": "🧍",
        "short": "🧍",
        "kind": "😇",
        "clever": "💡",
        "friendly": "🤝",
        "creative": "🎨",
        "neighbourhood": "🏡",
        "temple": "⛩️",
        "cathedral": "⛪",
        "suburb": "🏘️",
        "forest": "🌲",
        "mountain": "🏔️",
        "waterfall": "🌊",
        "desert": "🏜️",
        "wish": "✨",
        "fireworks": "🎆",
        "blossom": "🌸",
        "relative": "👨‍👩‍👧‍👦",
        "first footer": "👞",
        "badminton": "🏸",
        "champion": "🏆",
        "stadium": "🏟️",
        "fit": "💪",
        "marathon": "🏃",
        "continent": "🌍",
        "landmark": "🗽",
        "historic": "🏰",
        "modern": "🏙️",
        "peaceful": "🕊️",
        "recycle": "♻️",
        "reuse": "🔄",
        "reduce": "📉",
        "environment": "🌳",
        "plastic": "🍼",
        "hobby": "🎨",
        "gardening": "🪴",
        "coin": "🪙",
        "will": "🔮",
        "calories": "🔥",
        "diet": "🥗",
        "volunteer": "🤝",
        "donate": "🎁",
        "instrument": "🎸",
        "recipe": "📖",
        "monument": "🗿",
        "pedestrian": "🚶",
        "license": "🪪",
        "comedy": "😂",
        "solar": "☀️"
    };

    function getWordEmoji(word) {
        if (typeof word !== 'string') return FALLBACK_EMOJI;
        const clean = word.toLowerCase().trim();
        return EMOJI_FALLBACK[clean] || FALLBACK_EMOJI;
    }

    const EmojiUtils = {
        getWordEmoji: getWordEmoji,
        EMOJI_FALLBACK: EMOJI_FALLBACK,
        FALLBACK_EMOJI: FALLBACK_EMOJI
    };

    return EmojiUtils;
});
